### ISSUE TITLE
How to add seed data

### ISSUE THREAD

**Issue by dev-guy** [bitcrowd/carbonite#58]
Hello,

I have a script adds seed data by calling various Repo functions. The code is located in priv/repo/migrations/seed.exs. The code is below. It fails because of the foreign key constraints to the transaction table. I saw the README's reference to insert_migration_transaction/1 but the example doesn't pass any arguments to insert_migration_transaction. I tried passing a function - I didn't think it would work (it didn't) but I thought I'd give it a try.

```
** (RuntimeError) could not find migration runner process for #PID<0.94.0>
    (ecto_sql 3.9.0) lib/ecto/migration/runner.ex:304: Ecto.Migration.Runner.runner/0
    (ecto_sql 3.9.0) lib/ecto/migration/runner.ex:84: Ecto.Migration.Runner.migrator_direction/0
    (carbonite 0.5.0) lib/carbonite/migrations.ex:330: Carbonite.Migrations.insert_migration_transaction/2
```

Then I realized this script is not running as a migration.

I doubt this is a fixable problem since the functions called do not accept arguments relevant to a transaction. But I thought I would ask. I guess this needs to be rewritten as a migration.

Example:

```
if Mix.env() == :dev do
  PetalPro.Repo.delete_all(Log)
  PetalPro.Repo.delete_all(UserTOTP)
  PetalPro.Repo.delete_all(Invitation)
  PetalPro.Repo.delete_all(Membership)
  PetalPro.Repo.delete_all(Org)
  PetalPro.Repo.delete_all(UserToken)
  PetalPro.Repo.delete_all(User)

  admin = UserSeeder.admin()

  normal_user =
    UserSeeder.normal_user(%{
      email: "user@example.com",
      name: "Sarah Cunningham",
      password: "password",
      confirmed_at: Timex.now() |> Timex.to_naive_datetime()
    })
```

**Comment by dev-guy** [comment]
Thanks to https://github.com/bitcrowd/carbonite/search?q=insert_migration_transaction_after_begin%28%29
I was able to figure it out. My fix is below.

```
defmodule PetalPro.Repo.Migrations.SeedUsers do
  alias PetalPro.Accounts.{User, UserToken, UserTOTP, UserSeeder}
  alias PetalPro.Logs.Log
  alias PetalPro.Orgs.OrgSeeder
  alias PetalPro.Orgs.{Org, Membership, Invitation}
  use Ecto.Migration
  import Carbonite.Migrations
  insert_migration_transaction_after_begin()

  def change do
    if Mix.env() == :dev do
        PetalPro.Repo.delete_all(Log)
        PetalPro.Repo.delete_all(UserTOTP)
        PetalPro.Repo.delete_all(Invitation)
        PetalPro.Repo.delete_all(Membership)
        PetalPro.Repo.delete_all(Org)
        PetalPro.Repo.delete_all(UserToken)
        PetalPro.Repo.delete_all(User)

        admin = UserSeeder.admin()

        normal_user =
          UserSeeder.normal_user(%{
            email: "user@example.com",
            name: "Sarah Cunningham",
            password: "password",
            confirmed_at: Timex.now() |> Timex.to_naive_datetime()
          })

        org = OrgSeeder.random_org(admin)
        PetalPro.Orgs.create_invitation(org, %{email: normal_user.email})

        UserSeeder.random_users(20)
    end
  end
end
```

**Comment by maltoe** [comment]
Hey @dev-guy 

Since `seeds.exs` is a script and not a migration, in our projects we usually just use the "normal" way of inserting Carbonite transactions before inserting the seed data, e.g. something like:

```
Ecto.Multi.new()
|> Carbonite.Multi.insert_transaction(%{meta: %{type: "seeds"}})
|> Ecto.Multi.insert(:foo, %MyApp.Foo{})
|> MyApp.Repo.transaction()
```

But if your solution works for you, that's great too!

**Comment by andreasknoepfle** [comment]
Maybe to give some background here: 

Carbonite always needs a `Carbonite.Transation` record to be inserted alongside changes that one does on certain tables. Like this one always has a record referencing related data changes together into one transaction and carbonite can guarantee that there are no changes without such a transaction because of the table trigger. 

Since your seed data is also changes that are done on the tracked databases, they also need such a transaction to group them. You can do so like showcased above. 

Migrations also sometimes need to insert/update data into tables. Since they also need a transaction grouping them, there is the `insert_migration_transaction_after_begin` macro, that helps with this, so that inside of a migration (that will normally anyway run within a transaction) a `Carbonite.Transaction` record is created automatically. 
So by converting your seed data to be a migration, you can use the macro, that is normally made for migrations to create that record for you.

Hope this helps
Cheers
Andi

**Comment by dev-guy** [comment]
@maltoe, Thank you for the reply. Since the existing functions didn't accept any input parameters, I could not figure out how to pass transactions to it. Maybe Ecto has a magic default transaction. I don't know enough about Ecto yet unfortunately. In order to use Multi, I would have to change all of the existing code to throw exceptions. I think Elixir is flawed in this respect but that's a different thread.
